FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    apt-utils bison ca-certificates ccache check cmake curl \
    flex git gperf lcov libncurses-dev libusb-1.0-0-dev \
    locales make nano ninja-build python3 python3-pip \
    unzip vim wget xz-utils zip \
   && apt-get autoremove -y \
   && rm -rf /var/lib/apt/lists/* \
   && update-alternatives --install /usr/bin/python python /usr/bin/python3 10

RUN python -m pip install --no-cache-dir --upgrade pip virtualenv
COPY shallow_clone /usr/bin/ 

ENV IDF_TOOLS_PATH=/opt/esp
ENV IDF_PATH=/opt/esp/idf
ENV LIB_BUILDER_PATH=/opt/esp/lib-builder
RUN mkdir -p $LIB_BUILDER_PATH

ADD dist/xtensa-esp32-elf-linux64-1.22.0-97-gc752ad5-5.2.0.tar.gz $IDF_TOOLS_PATH
#RUN curl https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-97-gc752ad5-5.2.0.tar.gz | tar -xzC $IDF_TOOLS_PATH

RUN shallow_clone https://github.com/espressif/esp-idf 85c43024cb133cd81d3e3a95c1da49d51291d306 $IDF_PATH \
    && cd $IDF_PATH && git submodule update --progress --depth 1 --init --recursive \
    && rm $IDF_PATH/components/expat/expat/testdata/largefiles/* \
    && python -m pip install --no-cache-dir -r $IDF_PATH/requirements.txt

RUN shallow_clone https://github.com/espressif/esp32-arduino-lib-builder 9036908331c9a3803b022c2a030594be1daa2572 $LIB_BUILDER_PATH
RUN sed -i '40s!^!source tools/config.sh\n\n!; 41,46{s/^/#/}' $LIB_BUILDER_PATH/build.sh

RUN shallow_clone https://github.com/espressif/arduino-esp32 46d5afb17fb91965632dc5fef237117e1fe947fc $LIB_BUILDER_PATH/components/arduino \
      && rm -rf $LIB_BUILDER_PATH/components/arduino/tools/sdk
RUN shallow_clone https://github.com/espressif/esp32-camera/ 488c308b79af2a66c285f4319b746943d6b2f893 $LIB_BUILDER_PATH/components/esp32-camera
RUN shallow_clone https://github.com/espressif/esp-face/ 420fc7e219ba98e40a5493b9d4be270db2f2d724 $LIB_BUILDER_PATH/components/esp-face

RUN echo "PATH=$IDF_TOOLS_PATH/xtensa-esp32-elf/bin:$PATH\ncd $LIB_BUILDER_PATH" >> /root/.bashrc

